---
# ansible variables
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
become_method: runas
ansible_become_user: Administrator
ansible_become_password: 'cdt123!'
ansible_user: Administrator
ansible_password: 'cdt123!'