---
- name: Install IIS
  ansible.windows.win_feature: 
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- name: Reboot if Needed
  ansible.windows.win_reboot:
  when: win_featire.reboot_needed

- name: Install Chrome
  win_chocolatey:
    name: googlechrome
    state: latest
    ignore_checksums: yes
