---
- name: Install Chocolatey
  win_chocolate:
    name: chocolatey.server
    state: prsent

- name: Remove Default Website
  win_iis_website:
    name: Default Web Site
    state: absent

- name: create the Chocolatey IIS web app pool
  win_iis_webapppool:
    name: chocolatey_server_app_pool
    state: started
    attributes:
      enable32BitAppOnWin64: yes
      managedPipelineMode: Integrated
      managedRuntimeVersion: v4.0
      processModel.loadUserProfile: yes
      startMode: 1  # AlwaysRunning - need to use an int for Server 2008 R2 compat
  when: not ansible_check_mode  # fails when setting attributes in check mode
 
 - name: Grant read permissions to c:\tools\chocolatey.server
    win_acl:
      user: ""
      path: c:\tools\chocolatey.server
      rights: Read
      state: present
      type: allow
      inherit: ContainerInherit, ObjectInherit
      progagation: InheritOnly
  with_items:
    - IIS_IUSRS
    - IUSR
    - IIS APPPOOL\chocolatey_server_app_pool

- name: Grant read permissions to c:\tools\chocolatey.server
  win_acl:
    user: ""
    path: c:\tools\chocolatey.server
    rights: Modify
    state: present
    type: allow
    inherit: ContainerInherit, ObjectInherit
    progagation: InheritOnly
  with_items:
  - IIS_IUSRS
  - IUSR
  - IIS APPPOOL\chocolatey_server_app_pool

- name: Create IIS Website Chocolatey 
  win_iis_website:
    name: chocolatey_server_site
    state: started
    application_pool: chocolatey_server_app_pool
    port: 80
    physical_path: c:\tools\chocolatey.server

- name: Set API-Key
  win_lineinfile:
    path: c:\tools\chocolatey.server\web.config
    regexp: 'add key="apiKey"'
  when opt_chocolate_server_api_token is defined